OPENAI_API_KEY = "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"
ALPHA_VANTAGE_API_KEY = "XNBA77REHGPU08VZ"