OPENAI_API_KEY = "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"
ALPHA_VANTAGE_API_KEY = "XNBA77REHGPU08VZ"