OPENAI_API_KEY = "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"
ALPHA_VANTAGE_API_KEY = "XNBA77REHGPU08VZ"